DIR=$EXP/results


#RX_MISS	VPP_OUTPUT	VPP_INPUT	VPP_DROP	TOTAL
echo "########################"
echo ""
echo "Total=rx_miss+vpp_input;"
echo "This may not be correct always since rx_miss counter in vpp is not udated after every vector. This may account to slight  +- error in measurement"
echo ""
echo "########################"
echo ""

	i=$4
	WEIGHT=$3
	LIMIT=$(( $WEIGHT*14 ))
	while [[ $WEIGHT -le $LIMIT ]];do
		k=(FAIRDROP_CPU_"$WEIGHT"_2_"$1"SIZE FAIRDROP_CPU_"$WEIGHT"_2_"$2"SIZE)

		for j in 0 1 ;do
			TIME=20
			TIME_VPP=20.1

			# Total Million Packets per second generated by Dpdk-Pktgen.
			TOTAL=$(cat $DIR/"${k[$j]}"_"$i"/pktgenstats.dat | awk '{print $6}')
			TOTAL_RATE=$(python -c "print(round((($TOTAL/$TIME)/1000000.0),2))")

			#Input rate in Million Packets per second taken by the packet processing application-VPP
			VPP_INPUT=$(cat $DIR/"${k[$j]}"_"$i"/showrun.dat | grep dpdk-input | awk '{print $4}')
			VPP_INPUT_RATE=$(python -c "print(round((($VPP_INPUT/$TIME_VPP)/1000000.0),2))")

			#Output rate in Million Packets per second from VPP
			VPP_OUTPUT=$(cat $DIR/"${k[$j]}"_"$i"/showrun.dat | grep "TenGigabitEthernet84/0/1-out" | awk '{print $4}')
			VPP_OUTPUT_RATE=$(python -c "print(round((($VPP_OUTPUT/$TIME_VPP)/1000000.0),2))")

			#Rate in Million Packets per second dropped by VPP (Dropped by Fairdrop algorithm in vpp in this particular experimental setup)
			VPP_DROP=$(python -c "print($VPP_INPUT-$VPP_OUTPUT)")
			VPP_DROP_RATE=$(python -c "print(round((($VPP_DROP/$TIME_VPP)/1000000.0),2))")

			#Rate in Million Packets per second lost at interface level.
			RX_MISS=$(cat $DIR/"${k[$j]}"_"$i"/showint.dat | grep "rx-miss" |awk '{print $2}') #$(python -c "print($TOTAL-$VPP_INPUT)")
			if [[ $RX_MISS -gt 0 ]];then
				RX_MISS=$RX_MISS;
			else
				RX_MISS=0;
			fi
			RX_MISS_RATE=$(python -c "print(round((($RX_MISS/$TIME_VPP)/1000000.0),2))")

			echo -e "${k[$j]}\tPKT-SIZE: $i\tRX_MISS_RATE:\t$RX_MISS_RATE\tVPP_INPUT_RATE:\t$VPP_INPUT_RATE\tVPP_DROP_RATE:\t$VPP_DROP_RATE\tVPP_OUTPUT_RATE\t$VPP_OUTPUT_RATE\tTOTAL_RATE:\t$TOTAL_RATE"
		done
		WEIGHT=$(( $WEIGHT+$3 ))
		echo ""
	done
